### ISSUE TITLE
Update to latest API

### ISSUE THREAD

**Issue by danielfarrell** [efleming/sovren#5]
I'll make a pull request for this as I get a little time, but working on the current version of the Sovren API I had to use my own client class to make the API calls.  The classes in this library for parsing still worked great on the response, so it's just the client that needs updating.

**Comment by jdrago999** [comment]
Hi -- any movement on this? It's been a couple years...

**Comment by jdrago999** [comment]
Should this issue be closed now, since the PR has been merged?

**Comment by jdrago999** [comment]
Also should the gem's version - in lib/sovren/version.rb -- be updated?

**Comment by danielfarrell** [comment]
This got merged in on #9
